[VERSION]
version = 0.6.4

[LINUX]
3.10 = pysqlparser.cpython-310-x86_64-linux-gnu.so
3.11 = pysqlparser.cpython-311-x86_64-linux-gnu.so
3.12 = pysqlparser.cpython-312-x86_64-linux-gnu.so
3.13 = pysqlparser.cpython-313-x86_64-linux-gnu.so

[WINDOWS]
3.10 = pysqlparser.cp310-win_amd64.pyd
3.11 = pysqlparser.cp311-win_amd64.pyd
3.12 = pysqlparser.cp312-win_amd64.pyd
3.13 = pysqlparser.cp313-win_amd64.pyd
3.14 = pysqlparser.cp314-win_amd64.pyd
